#!/usr/bin/env python3
"""
GCP Firewall Rule Setup for eBay Webhook
"""

print("🔥 GCP FIREWALL SETUP FOR EBAY WEBHOOK")
print("=" * 50)
print()
print("✅ Your webhook server is running on port 8443")
print("🎯 We need to create a firewall rule to allow eBay access")
print()
print("📋 OPTION 1: Using GCP Console (Recommended)")
print("-" * 40)
print("1. Go to: https://console.cloud.google.com/networking/firewalls/list")
print("2. Click 'CREATE FIREWALL RULE'")
print("3. Fill in these details:")
print("   - Name: allow-ebay-webhook-8443")
print("   - Direction: Ingress")
print("   - Action: Allow")
print("   - Targets: All instances in the network")
print("   - Source IP ranges: 0.0.0.0/0")
print("   - Protocols and ports: Specified protocols and ports")
print("   - TCP: Check the box and enter: 8443")
print("4. Click 'CREATE'")
print()
print("📋 OPTION 2: Using gcloud command")
print("-" * 40)
print("Run this command in your local terminal (not in this VM):")
print("gcloud compute firewall-rules create allow-ebay-webhook-8443 \\")
print("  --allow tcp:8443 \\")
print("  --source-ranges 0.0.0.0/0 \\")
print("  --description 'Allow eBay webhook access on port 8443'")
print()
print("📋 OPTION 3: Quick test without firewall")
print("-" * 40)
print("First, let's test if the firewall is actually blocking:")
print("1. Go to: https://pokemon-arbitrage.duckdns.org:8443/health")
print("2. If it loads, the firewall is already open!")
print("3. If it doesn't load, we need the firewall rule")
print()
print("🎯 CURRENT ENDPOINT FOR EBAY:")
print("https://pokemon-arbitrage.duckdns.org:8443/marketplace-deletion")
print()
print("✅ Once firewall rule is created, eBay should be able to validate!"))
