#!/bin/bash

echo "🐙 GitHub Repository Setup for Railway Deployment"
echo "=================================================="
echo ""
echo "We need to create a GitHub repository to deploy to Railway."
echo "Here are your options:"
echo ""
echo "📋 OPTION 1: Manual GitHub Setup (Recommended)"
echo "1. Go to https://github.com/new"
echo "2. Repository name: pokemon-arbitrage-webhook"
echo "3. Make it Public (required for Railway free tier)"
echo "4. Don't initialize with README (we already have files)"
echo "5. Click 'Create repository'"
echo ""
echo "📋 Then run these commands:"
echo "git remote add origin https://github.com/YOUR_USERNAME/pokemon-arbitrage-webhook.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "📋 OPTION 2: Use GitHub CLI (if you have it installed)"
echo "gh repo create pokemon-arbitrage-webhook --public --push"
echo ""
echo "🚀 After GitHub setup, proceed with Railway deployment:"
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Click 'Deploy from GitHub repo'"
echo "4. Select your pokemon-arbitrage-webhook repository"
echo "5. Add environment variables:"
echo "   TG_TOKEN=7688729602:AAEoi5jAtR-n3XOxJI7DSonbLoqJSEXaXvA"
echo "   EBAY_VERIFICATION_TOKEN=pokemon_arbitrage_secure_token_2025_ebay_compliance_abc123"
echo "6. Deploy!"
echo ""
echo "Your Railway URL will be: https://pokemon-arbitrage-webhook-[random].up.railway.app"
echo "eBay endpoint: https://pokemon-arbitrage-webhook-[random].up.railway.app/marketplace-deletion"
