[build]
builder = "RAILPACK"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --workers 4 --log-level info --timeout 120 --bind 0.0.0.0:$PORT app:application"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
FLASK_ENV = "production"
PYTHON_VERSION = "3.13.3"

[service]
regions = ["us-east"]
resources = {memory = "1024", cpu = 2}
internal_port = 8080