# Render.com deployment configuration
# Render auto-detects this file for Python apps
services:
  - type: web
    name: pokemon-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: EBAY_VERIFICATION_TOKEN
        sync: false
